# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [11]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key
if g_key == "YOUR KEY HERE!":
    import sys
    path = "/Users/matth/Desktop"
    sys.path.insert(0, path)
    from API_Keys import api_key
    g_key= api_key["Google Maps Platform"]

from api_keys import weather_api_key
if weather_api_key == "YOUR KEY HERE!":
    import sys
    path = "/Users/matth/Desktop"
    sys.path.insert(0, path)
    from API_Keys import api_key
    weather_api_key= api_key["https://openweathermap.org/"]

# input csv
input_csv = "../output_data/cities.csv"

#import pretty print
import pprint as pprint

# configure gmaps with api key
gmaps.configure(api_key=g_key)

#for sleep
import time

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [12]:
city_weather = pd.read_csv("../output_data/cities.csv",index_col=0)
city_weather

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,isla vista,34.4133,-119.8610,57.00,58.0,75.0,3.44,US,1.615496e+09
1,qaanaaq,77.4840,-69.3632,1.76,61.0,48.0,2.51,GL,1.615496e+09
2,kapaa,22.0752,-159.3190,73.40,88.0,40.0,6.91,US,1.615496e+09
3,cherskiy,68.7500,161.3000,-13.56,76.0,0.0,5.08,RU,1.615496e+09
4,ayan,56.4500,138.1667,8.58,67.0,0.0,8.95,RU,1.615496e+09
...,...,...,...,...,...,...,...,...,...
553,birjand,32.8663,59.2211,48.20,20.0,0.0,4.61,IR,1.615496e+09
554,usevya,-7.1000,31.2333,67.14,91.0,44.0,1.23,TZ,1.615496e+09
555,corner brook,48.9667,-57.9484,33.80,93.0,90.0,12.66,CA,1.615496e+09
556,uvira,-3.4067,29.1458,74.41,76.0,93.0,1.70,CD,1.615496e+09
557,tura,25.5198,90.2201,68.47,48.0,0.0,2.89,IN,1.615496e+09

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [13]:
# !jupyter nbextension enable --py gmaps

Enabling notebook extension jupyter-gmaps/extension...
      - Validating: ok

In [14]:
# Plot Heatmap
fig = gmaps.figure()

# Create heat layer
heat_layer = gmaps.heatmap_layer(city_weather[["Lat","Lng"]], weights=city_weather["Humidity"], 
                                 dissipating=False, max_intensity=city_weather["Humidity"].max(),
                                 point_radius=3)


# Add layer
fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [15]:
# * Narrow down the DataFrame to find your ideal weather condition. For example:
#   * A max temperature lower than 80 degrees but higher than 70.
#   * Wind speed less than 10 mph.
#   * Zero cloudiness.
#   * Drop any rows that don't contain all three conditions. You want to be sure the weather is ideal.
ideal_weather = city_weather[(city_weather["Max Temp"]>70)&\
              (city_weather["Max Temp"]<80)&\
              (city_weather["Wind Speed"]<10)&\
              (city_weather["Cloudiness"]==0)].reset_index(drop=True)
ideal_weather

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,saint-philippe,-21.3585,55.7679,75.20,57.0,0.0,6.91,RE,1.615496e+09
1,riyadh,24.6877,46.7219,78.80,20.0,0.0,6.91,SA,1.615496e+09
2,muscat,23.6139,58.5922,78.80,41.0,0.0,3.44,OM,1.615496e+09
3,narasannapeta,18.4167,84.0500,72.57,91.0,0.0,4.21,IN,1.615496e+09
4,aswan,24.0934,32.9070,78.12,21.0,0.0,9.06,EG,1.615496e+09
5,cidreira,-30.1811,-50.2056,74.88,67.0,0.0,8.63,BR,1.615496e+09
6,correia pinto,-27.5847,-50.3611,70.84,54.0,0.0,3.53,BR,1.615496e+09
7,gangakher,18.9500,76.7500,78.91,18.0,0.0,9.22,IN,1.615496e+09
8,prieska,-29.6641,22.7474,70.07,29.0,0.0,2.91,ZA,1.615496e+09
9,inhambane,-23.8650,35.3833,75.85,86.0,0.0,7.61,MZ,1.615496e+09
10,sur,22.5667,59.5289,77.23,38.0,0.0,5.61,OM,1.615496e+09
11,salalah,17.0151,54.0924,75.20,35.0,0.0,3.44,OM,1.615496e+09
12,saint-joseph,-21.3667,55.6167,75.20,57.0,0.0,6.91,RE,1.615496e+09
13,palasa,18.7667,84.4167,71.60,82.0,0.0,5.99,IN,1.615496e+09
14,srivardhan,18.0333,73.0167,73.17,64.0,0.0,4.29,IN,1.615496e+09
15,buraydah,26.3260,43.9750,73.40,43.0,0.0,3.44,SA,1.615496e+09
16,saint-pierre,-21.3393,55.4781,75.20,57.0,0.0,6.91,RE,1.615496e+09
17,tsabong,-26.0217,22.4010,79.74,13.0,0.0,8.21,BW,1.615496e+09

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [16]:
hotel_df = ideal_weather
hotel_df["Hotel Name"]=""
hotel_df

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name
0,saint-philippe,-21.3585,55.7679,75.20,57.0,0.0,6.91,RE,1.615496e+09,
1,riyadh,24.6877,46.7219,78.80,20.0,0.0,6.91,SA,1.615496e+09,
2,muscat,23.6139,58.5922,78.80,41.0,0.0,3.44,OM,1.615496e+09,
3,narasannapeta,18.4167,84.0500,72.57,91.0,0.0,4.21,IN,1.615496e+09,
4,aswan,24.0934,32.9070,78.12,21.0,0.0,9.06,EG,1.615496e+09,
5,cidreira,-30.1811,-50.2056,74.88,67.0,0.0,8.63,BR,1.615496e+09,
6,correia pinto,-27.5847,-50.3611,70.84,54.0,0.0,3.53,BR,1.615496e+09,
7,gangakher,18.9500,76.7500,78.91,18.0,0.0,9.22,IN,1.615496e+09,
8,prieska,-29.6641,22.7474,70.07,29.0,0.0,2.91,ZA,1.615496e+09,
9,inhambane,-23.8650,35.3833,75.85,86.0,0.0,7.61,MZ,1.615496e+09,
10,sur,22.5667,59.5289,77.23,38.0,0.0,5.61,OM,1.615496e+09,
11,salalah,17.0151,54.0924,75.20,35.0,0.0,3.44,OM,1.615496e+09,
12,saint-joseph,-21.3667,55.6167,75.20,57.0,0.0,6.91,RE,1.615496e+09,
13,palasa,18.7667,84.4167,71.60,82.0,0.0,5.99,IN,1.615496e+09,
14,srivardhan,18.0333,73.0167,73.17,64.0,0.0,4.29,IN,1.615496e+09,
15,buraydah,26.3260,43.9750,73.40,43.0,0.0,3.44,SA,1.615496e+09,
16,saint-pierre,-21.3393,55.4781,75.20,57.0,0.0,6.91,RE,1.615496e+09,
17,tsabong,-26.0217,22.4010,79.74,13.0,0.0,8.21,BW,1.615496e+09,

In [17]:
# https://developers.google.com/maps/documentation/places/web-service/supported_types?hl=en_US
#supported types for hotels is probably "lodging"
#URL example found at https://developers.google.com/maps/documentation/places/web-service/get-api-key?hl=en_US
#https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=-33.8670522,151.1957362&radius=500&types=food&name=harbour&key=YOUR_API_KEY
radius=5000
types="lodging"
key=g_key

for i in hotel_df.index:
    location=f"{hotel_df['Lat'][i]},{hotel_df['Lng'][i]}"
    url = f"https://maps.googleapis.com/maps/api/place/nearbysearch/json?location={location}&radius={radius}&types={type}&key={g_key}"
    try:
        response=requests.get(url).json()
        time.sleep(0.5)
        hotel_df["Hotel Name"][i]=response["results"][1]["name"]
    except:
        hotel_df["Hotel Name"][i]=float("NaN")
#clears g_key (api key) after use.
g_key=[]
url = []

<ipython-input-17-7ce3e5d976c9>:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hotel_df["Hotel Name"][i]=response["results"][1]["name"]

In [18]:
hotel_df

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name
0,saint-philippe,-21.3585,55.7679,75.20,57.0,0.0,6.91,RE,1.615496e+09,"Chambres d'hôte ""La Trinité"""
1,riyadh,24.6877,46.7219,78.80,20.0,0.0,6.91,SA,1.615496e+09,InterContinental Riyadh
2,muscat,23.6139,58.5922,78.80,41.0,0.0,3.44,OM,1.615496e+09,Mutrah Hotel
3,narasannapeta,18.4167,84.0500,72.57,91.0,0.0,4.21,IN,1.615496e+09,Mahesh Traders
4,aswan,24.0934,32.9070,78.12,21.0,0.0,9.06,EG,1.615496e+09,Nuba Nile
5,cidreira,-30.1811,-50.2056,74.88,67.0,0.0,8.63,BR,1.615496e+09,Diego Imóveis
6,correia pinto,-27.5847,-50.3611,70.84,54.0,0.0,3.53,BR,1.615496e+09,CASAN-Companhia Catarinense de Água e Saneamento
7,gangakher,18.9500,76.7500,78.91,18.0,0.0,9.22,IN,1.615496e+09,Sai Packers and Movers
8,prieska,-29.6641,22.7474,70.07,29.0,0.0,2.91,ZA,1.615496e+09,R.D. Williams Primere Skool
9,inhambane,-23.8650,35.3833,75.85,86.0,0.0,7.61,MZ,1.615496e+09,Oceano
10,sur,22.5667,59.5289,77.23,38.0,0.0,5.61,OM,1.615496e+09,Sur Plaza Hotel
11,salalah,17.0151,54.0924,75.20,35.0,0.0,3.44,OM,1.615496e+09,HAMDAN PLAZA HOTEL SALALAH
12,saint-joseph,-21.3667,55.6167,75.20,57.0,0.0,6.91,RE,1.615496e+09,"""Plantation Bed and Breakfast"
13,palasa,18.7667,84.4167,71.60,82.0,0.0,5.99,IN,1.615496e+09,"LIC of India, Branch Office"
14,srivardhan,18.0333,73.0167,73.17,64.0,0.0,4.29,IN,1.615496e+09,Savli Resort/Hotel - Shrivardhan
15,buraydah,26.3260,43.9750,73.40,43.0,0.0,3.44,SA,1.615496e+09,فندق راحة السلام
16,saint-pierre,-21.3393,55.4781,75.20,57.0,0.0,6.91,RE,1.615496e+09,Alizé Plage
17,tsabong,-26.0217,22.4010,79.74,13.0,0.0,8.21,BW,1.615496e+09,PEP Tsabong

In [19]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [28]:
# Add marker layer ontop of heat map
hotel_layer = gmaps.marker_layer(locations, \
                                 info_box_content=[f"{info}" for info in hotel_info])

# Add layers and Display figure
fig.add_layer(heat_layer)
fig.add_layer(hotel_layer)


fig

Figure(layout=FigureLayout(height='420px'))